#!/bin/bash

ask_yes_no() {
    while true; do
        read -p "Proceed ? [Y/n] " yn
        case $yn in
            [Yy]* | "" ) return 0;;  # Treat "Y", "y", or Enter as "yes"
            [Nn]* ) return 1;;       # Treat "N" or "n" as "no"
            * ) echo "Please answer yes (Y) or no (N).";;
        esac
    done
}

console_keyboard_font() {
  echo "Setting Console Keyboard Layout to EN...."
  if ask_yes_no; then
    loadkeys en
    
  else
    while true; do
      localectl list-keymaps
      clear
      read -p "Enter the your keyboard-layout : " layout
      loadkeys $layout
      if [ $? -eq 0 ]; then
          break
      else
        echo "Enter a valid input"
        sleep 2
      
      fi
    done
  fi
  echo "Layout Loded...."
  sleep 2
}


check_uefi() {
  if [ -d /sys/firmware/efi ]; then
    echo "System is booted in UEFI mode."
  else
    echo "System is booted in Legacy BIOS mode."
  fi
  echo "Kindly remember you'r boot, it might be a key for further steps."
  echo "If you are not satisfid then, Kindly Chnage You BOOT."
  sleep 2
}

check_internet() {
  ping -c 1 8.8.8.8 > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "Internet working...."
    sleep 2
  else
    echo "Internet Not Working..."
    echo "Please Connect to a Network , this script need internt connecitom | "
    sleep 2
    exit
  fi
}

time_date() {
  timedatectl set-ntp true
  
  echo "Setting Time Zone to Asia/Calcutta...."
  if ask_yes_no; then
    timedatectl set-timezone Asia/Calcutta
    
  else
    while true; do
    timedatectl list-timezones
    clear
    read -p "Enter the your TimeZone : " tmz
    timedatectl set-timezone $tmz
    if [ $? -eq 0 ]; then
        break
    else
        echo "Enter a valid input"
        sleep 2
    fi
    done
  fi
}

update_mirrors() {
  echo "Do You Want to Update Your mirrors list, it will porvide you with faster download speed"
  echo "This file will also be coppied to the newly installed arch system"
  sleep 2
  if ask_yes_no; then
    reflector -l 25 –-sort rate –-verbose –-download-timeout 10 –-save /etc/pacman.d/mirrorlist
  else
    echo "Not Update you mirror list"
  fi
  sleep 1
}

echo "Settign Console Font : Ter-v24b...."
setfont ter-v24b
sleep 1
clear

echo -ne "
-------------------------------------------------------------------------
                       █████╗ ██████╗  ██████╗██╗  ██╗██╗
                      ██╔══██╗██╔══██╗██╔════╝██║  ██║██║
                      ███████║██████╔╝██║     ███████║██║
                      ██╔══██║██╔══██╗██║     ██╔══██║██║
                      ██║  ██║██║  ██║╚██████╗██║  ██║██║
                      ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝
-------------------------------------------------------------------------
                      Minimalist Arch Linux Installer
-------------------------------------------------------------------------
                      
"
check_internet
echo -ne "

-------------------------------------------------------------------------
                          Setting Up Basics
-------------------------------------------------------------------------
"
console_keyboard_font
time_date
echo -ne "
-------------------------------------------------------------------------
                     Disk Managment and Partition     
-------------------------------------------------------------------------
"

./partition

echo -ne "
-------------------------------------------------------------------------
                    Setting up mirrors for optimal download 
-------------------------------------------------------------------------
"
update_mirrors