#!/bin/bash

echo -ne "
-------------------------------------------------------------------------
                     Disk Managment and Partition     
-------------------------------------------------------------------------
"

choice_d() {

echo "Do you want to manually edit-the filesystem"
echo "NOITCE : Using Automatic will wipe yor disk..."
echo " [0] : Manual"
echo " [1] : Automatic (default)"
while true; do
        read n
        case $n in
            [1]* | "" ) return 0;;  # Treat "Y", "y", or Enter as "yes"
            [0]* ) return 1;;       # Treat "N" or "n" as "no"
            * ) echo "Please answer yes (Y) or no (N).";;
        esac
    done
}


if choice_d; then
  # Automatic
  

  

else

fi
  # Manual
  echo "You have Choose the manual option"
  DISK=$(ask_for_disk)
  fdisk $DISK
echo "Do you want to set up LVM"




