#!/bin/bash
stty erase ^H
echo -ne "
-------------------------------------------------------------------------
                     Installing Essestial Packages     
-------------------------------------------------------------------------
"

ask_yes_no() {
    while true; do
        read -p "Proceed ? [Y/n] " yn
        case $yn in
            [Yy]* | "" ) return 0;;  # Treat "Y", "y", or Enter as "yes"
            [Nn]* ) return 1;;       # Treat "N" or "n" as "no"
            * ) echo "Please answer yes (Y) or no (N).";;
        esac
    done
}

inst_base_pkg() {
echo -ne "
--------------------------- Base Pakages --------------------------
"
  echo "Installing Base Pakages..."
  pacman -S linux-lts linux-lts-headers linux-firmware

echo -ne "
--------------------------- Essestial Pakages --------------------------
"
  echo "Installing Essestial Pakages...." 
  pacman -S sudo base-devel grub efibootmgr networkmanager lvm2 mtools os-prober dosfstools vim

echo -ne "
--------------------------- Display Dirvers --------------------------
"
  echo "Do you want to install DISPLAY Drivers for INTEL"
  if ask_yes_no; then
    pacman -S mesa xf86-video-intel
    
  else
  echo -ne "
-------------------------------------------------------------------------
              WE ARE HUMBALLY SOORY ,WE DOTN HAVE OTHER DIVERS 
            SET IN OUR LIBRARY... YOU HAVE TO INSTALL'EM MNUALLY
-------------------------------------------------------------------------
"
fi
}


host_name() {
  echo "Generating Hosts file....."
  touch /etc/hostname
  echo "[ Default : archlinux ]"
  read -p "Enter you'r hostname : " hst
  if [ -z "$hst" ]; then
    echo $hst > /etc/hostname
  else
    echo "archlinux" >> /etc/hostname
  fi
}

inst_base_pkg
host_name

